# Generated by Django 5.1.3 on 2024-12-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_payment_method_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('COD', 'Cash on Delivery'), ('Debit', 'Debit Card'), ('MM', 'Mobile Money'), ('PayPal', 'PayPal')], max_length=20, null=True),
        ),
    ]
